Repository fineanmol/Hacktoberfest2025, pull requests merged in 2021-10, with the labels that each got.

#143 Majority element using Moore's voting algorithm
  Program's_Contributed_By_Contributors/MajorityElement.cpp
Labels: question

#169 Added new file
  Contributors.html
  Program's_Contributed_By_Contributors/Java_Programs/Finobbaci.java
Labels: Need Fix (Conflict pull request)

#177 added my name to contributors.html
  Contributors.html
Labels: Need Fix (Conflict pull request)

#179 Added fizbuzz program and updated contributor list
  Contributors.html
  Program's_Contributed_By_Contributors/Python_Programs/fizzbuz.py
Labels: Need Fix (Conflict pull request)

#185 Breadth First Search algorithm
  Contributors.html
  Program's_Contributed_By_Contributors/Java_Programs/Misc/BFS.java
Labels: Need Fix (Conflict pull request)

#206 added myself to contributions.html
  Contributors.html
Labels: hacktoberfest-accepted

#234 Create helloworld.cpp
  Program's_Contributed_By_Contributors/C++_Programs/helloworld.cpp
Labels: Name missing in Contribution.html

#252 Add files via upload
  Program's_Contributed_By_Contributors/HTML Designs/Responsive/My first doc.html
  Program's_Contributed_By_Contributors/HTML Designs/Responsive/about.html
  Program's_Contributed_By_Contributors/HTML Designs/Responsive/about.txt
  Program's_Contributed_By_Contributors/HTML Designs/Responsive/fav.png
  Program's_Contributed_By_Contributors/HTML Designs/Responsive/favicon.ico
  Program's_Contributed_By_Contributors/HTML Designs/Responsive/favicon.zip
  Program's_Contributed_By_Contributors/HTML Designs/Responsive/jyt.jfif
Labels: Name missing in Contribution.html

#250 Create bitset_count.cpp
  Program's_Contributed_By_Contributors/C++_Programs/bitset_count.cpp
Labels: Name missing in Contribution.html

#249 Create flappy.py
  Contributors.html
  Program's_Contributed_By_Contributors/Python_Programs/flappy.py
Labels: Name missing in Contribution.html

#257 Create maze.py
  Program's_Contributed_By_Contributors/Python_Programs/maze.py
Labels: Name missing in Contribution.html

#268 array Intersection program
  Contributors.html
  Program's_Contributed_By_Contributors/Java_Programs/arrayIntersection.java
Labels: Name missing in Contribution.html

#264 Hacks
  .DS_Store
  Contributors.html
  Typescript/.DS_Store
  Typescript/Basics/.gitignore
  Typescript/Basics/README.md
  Typescript/Basics/package-lock.json
  Typescript/Basics/package.json
  Typescript/Basics/public/favicon.ico
  Typescript/Basics/public/index.html
  Typescript/Basics/public/logo192.png
  Typescript/Basics/public/logo512.png
  Typescript/Basics/public/manifest.json
  Typescript/Basics/public/robots.txt
  Typescript/Basics/src/App.css
  Typescript/Basics/src/App.test.tsx
  Typescript/Basics/src/App.tsx
  Typescript/Basics/src/index.css
  Typescript/Basics/src/index.tsx
  Typescript/Basics/src/logo.svg
  Typescript/Basics/src/react-app-env.d.ts
  Typescript/Basics/src/reportWebVitals.ts
  Typescript/Basics/src/setupTests.ts
  Typescript/Basics/tsconfig.json
Labels: Name missing in Contribution.html

#289 Added Zoom Automation Python Script
  Contributors.html
  Program's_Contributed_By_Contributors/Python_Programs/Zoom_automation.py
Labels: Name missing in Contribution.html

#288 Updated style.css Please accept my PR
  styles.css
Labels: Name missing in Contribution.html

#286 stats,transitions,heading enhancement
  Contributors.html
  css/contributors.css
Labels: Name missing in Contribution.html

#287 Added python linked list implementation
  Program's_Contributed_By_Contributors/Python_Programs/linked_list.py
Labels: Name missing in Contribution.html

#281 Create Snake water gun.py
  Program's_Contributed_By_Contributors/Python_Programs/Snake water gun.py
Labels: Name missing in Contribution.html

#351 Create towerofhanoi.java
  Program's_Contributed_By_Contributors/Java_Programs/towerofhanoi.javaTower of Hanoi is a mathematical puzzle where we have three rods and n disks. The objective of the puzzle is to move the entire stack to another rod, obeying the following simple rules: 1) Only one disk can be moved at a time. 2) Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack i.e. a disk can only be moved if it is the uppermost disk on a stack. 3) No disk may be placed on top of a smaller disk.
Labels: Name missing in Contribution.html

#345 Added calender.py
  Program's_Contributed_By_Contributors/Python_Programs/calender.py
Labels: Name missing in Contribution.html

#318 added diameter of binary tree
  Contributors.html
  Program's_Contributed_By_Contributors/C++_Programs/Diameter of binary tree.cpp
Labels: hacktoberfest-accepted

#329 lcmreturnrecursion
  Contributors.html
  Program's_Contributed_By_Contributors/C++_Programs/factoralrecursion.cpp
  Program's_Contributed_By_Contributors/C++_Programs/lcmreturnrecursion.cpp
Labels: hacktoberfest-accepted

#369 Text to Handwriting file added
  Program's_Contributed_By_Contributors/Python_Programs/Fetch HTTP status code.py
  Program's_Contributed_By_Contributors/Python_Programs/qrcodepy.py
  Program's_Contributed_By_Contributors/Python_Programs/texttohandwritten.py
  Program's_Contributed_By_Contributors/Python_Programs/typingspeed.py
  Program's_Contributed_By_Contributors/Python_Programs/urlloadingtime.py
Labels: Name missing in Contribution.html

#414 Java Programs
  Java_Program/Bubble_sort.java
  Java_Program/Frequency of number in array.java
  Java_Program/binary_search.java
  Java_peograms/Bubble_sort.java
Labels: Name missing in Contribution.html

#420 Added Roll_dice.py and updated contributors.html
  Contributors.html
  Program's_Contributed_By_Contributors/Python_Programs/Roll_dice.py
Labels: hacktoberfest-accepted

#386 Friday artificial Assistant in python
  Program's_Contributed_By_Contributors/Python_Programs/friday.py
Labels: Name missing in Contribution.html

#421 InnocenDaksh63/calculator.java
  InnocentDaksh63
Labels: Name missing in Contribution.html

#324 Added a Java Program Reverse Number
  Program's_Contributed_By_Contributors/Java_Programs/Misc/ReverseNumber
Labels: Name missing in Contribution.html

#328 Create helloworld.cpp
  Program's_Contributed_By_Contributors/helloworld.cpp
Labels: Name missing in Contribution.html

#332 stringcompression.java
  Program's_Contributed_By_Contributors/Java_Programs/mthakur7_StringCompression.java
Labels: Name missing in Contribution.html

#365 InsertionSort.py
  Contributors.html
  InsertionSort.py
Labels: Need Fix (Conflict pull request), Name missing in Contribution.html

#418 Create QuickSort.java
  Java_Program/QuickSort.java
Labels: Name missing in Contribution.html

#375 polynomial calculations linked list
  Program's_Contributed_By_Contributors/C++_Programs/polynomiallinedlist.cpp
Labels: Name missing in Contribution.html

#373 Create Rod_Cutting.java
  Program's_Contributed_By_Contributors/Java_Programs/DP/Rod_Cutting.java
Labels: Name missing in Contribution.html

#362 Added Check prime programme
  Program's_Contributed_By_Contributors/Java_Programs/Checkprime.java
Labels: hacktoberfest-accepted, duplicate-pull-request

#358 Create VampireNumber.java
  Program's_Contributed_By_Contributors/Java_Programs/VampireNumber.java
Labels: hacktoberfest-accepted, duplicate-pull-request

#356 Create SpiralMatrix.java
  Program's_Contributed_By_Contributors/Java_Programs/SpiralMatrix.java
Labels: hacktoberfest-accepted, duplicate-pull-request

#352 Create SpiralMatrix.java
  Program's_Contributed_By_Contributors/SpiralMatrix.java
Labels: hacktoberfest-accepted, duplicate-pull-request

#348 Create KeithNumber.java
  Program's_Contributed_By_Contributors/Java_Programs/Misc/KeithNumber.java
Labels: hacktoberfest-accepted, duplicate-pull-request

#344 Create Diasarium.java
  Program's_Contributed_By_Contributors/Java_Programs/Diasarium.java
Labels: hacktoberfest-accepted, duplicate-pull-request

#342 Create MatrixMultiply.java
  Program's_Contributed_By_Contributors/Java_Programs/MatrixMultiply.java
Labels: hacktoberfest-accepted, duplicate-pull-request

#339 Create PalindromeArray.java
  Program's_Contributed_By_Contributors/Java_Programs/Misc/PalindromeArray.java
Labels: hacktoberfest-accepted, duplicate-pull-request

#334 Create tripletrouble.java
  Program's_Contributed_By_Contributors/Java_Programs/tripletrouble.java
Labels: hacktoberfest-accepted, duplicate-pull-request

#313 Added Codes to DP
  Program's_Contributed_By_Contributors/Dynamic Programming/Minimum number of deletions and insertions.cpp
Labels: hacktoberfest-accepted, duplicate-pull-request

#442 Added Caesar cypher.cpp HacktoberFest
  Contributors.html
  Program's_Contributed_By_Contributors/C++_Programs/Caesar_Cypher.cpp
Labels: bug, Need Fix (Conflict pull request)

#488 Added two recursion programs
  Contributors.html
  Program's_Contributed_By_Contributors/Recursion/factorial_n.cpp
  Program's_Contributed_By_Contributors/Recursion/n_fabonacci_series.cpp
Labels: hacktoberfest-accepted

#450 Create multiplication_table.cpp
  Program's_Contributed_By_Contributors/C++_Programs/multiplication_table.cpp
Labels: hacktoberfest-accepted

#451 Create printing G_pattern
  Program's_Contributed_By_Contributors/Python_Programs/printing G_pattern
Labels: hacktoberfest-accepted

#526 Added Problem in C++_ Programs
  Contributors.html
  Program's_Contributed_By_Contributors/C++_Programs/De_Brujin_Sequence.cpp
Labels: bug, hacktoberfest-accepted, Need Fix (Conflict pull request)

#564 contributed chocolate distribution problem with solution
  Contributors.html
  Program's_Contributed_By_Contributors/C++ Programs/chocolate_distribution.cpp
Labels: hacktoberfest-accepted
