Repository fineanmol/Hacktoberfest2025, pull requests merged in 2022-10, with the labels that each got.

#1840 Added Union Find/Disjoint set to python programs
  Program's_Contributed_By_Contributors/Python_Programs/union_find.py
Labels: hacktoberfest-accepted

#1839 added LinkedlistOperations.c
  Program's_Contributed_By_Contributors/Implementation_of_DS/LinkedlistOperations.c
Labels: hacktoberfest-accepted

#1838 some sorting Algo
  Program's_Contributed_By_Contributors/C++/Bubble_Sort.cpp
  Program's_Contributed_By_Contributors/C++/Insertion_sort.cpp
Labels: enhancement, hacktoberfest-accepted

#1835 I have added java Program for rock paper scissors game
  Program's_Contributed_By_Contributors/Java_Programs/Data_structure/RockPaperScissor.java
  css/LoginPage.html
Labels: enhancement, hacktoberfest-accepted

#1833 Updated contributors.html
  Contributors.html
Labels: enhancement, hacktoberfest-accepted

#1830 Create Floyd_Warshall.cpp
  Program's_Contributed_By_Contributors/C++/Floyd_Warshall.cpp
Labels: enhancement, hacktoberfest-accepted

#1831 Create Excersice_Circular RMQ
  Program's_Contributed_By_Contributors/C++/Excersice_Circular RMQ
Labels: enhancement, hacktoberfest-accepted

#1826 maximum rectangle sum
  Program's_Contributed_By_Contributors/rectangle sum.cpp
Labels: enhancement, hacktoberfest-accepted

#1825 Added OpenWeather CLI python script
  Program's_Contributed_By_Contributors/openweather_cli.py
Labels: enhancement, hacktoberfest-accepted

#1823 A To do list.
  .vscode/settings.json
  Contributors.html
  frontend projects/To-do-list/To-do-list.css
  frontend projects/To-do-list/To-do-list.html
  frontend projects/To-do-list/To-do-list.js
Labels: enhancement, hacktoberfest-accepted

#1822 Create reverse_pairs.cpp
  Program's_Contributed_By_Contributors/C++/reverse_pairs.cpp
Labels: enhancement, hacktoberfest-accepted

#1820 Doubly Linked LIst operations.
  Program's_Contributed_By_Contributors/C++/Doubly_LinkedList.cpp
Labels: enhancement, hacktoberfest-accepted

#1819 @ files on competitive programming questions
  Counting Bits
  FibonacciNumber
Labels: enhancement, hacktoberfest-accepted

#1817 Added MaxDifferenceInArray.cpp
  Program's_Contributed_By_Contributors/C++/MaxDifferenceInArray.cpp
Labels: enhancement, hacktoberfest-accepted

#1816 added Stack reverse
  Program's_Contributed_By_Contributors/Java_Programs/Data_structure/Stack reverse.java
Labels: enhancement, hacktoberfest-accepted

#1813 Create Palindrome.py
  Program's_Contributed_By_Contributors/Python_Programs/Palindrome.py
Labels: enhancement, hacktoberfest-accepted

#1806 Modularise main script and add missing alt attributes to images
  Contributors.html
  contributors/data.js
Labels: enhancement, hacktoberfest-accepted

#1821 Update Contributors.html
  Contributors.html
Labels: enhancement, hacktoberfest-accepted

#1804 fix: search Contributor input width fix and autofill color issue
  css/contributors.css
Labels: enhancement, hacktoberfest-accepted

#2186 CSS - Text Animation
  css/animation.css
Labels: hacktoberfest-accepted

#2185 N QUEEN IN PYTHON
  N QUEEN.py
Labels: hacktoberfest-accepted

#2184 Update README.md
  README.md
Labels: hacktoberfest-accepted

#2183 Java Practise Programs
  Simple Java Programs/Fruitshop.java
  Simple Java Programs/Green.java
  Simple Java Programs/Java.txt
  Simple Java Programs/area.java
  Simple Java Programs/perfect.java
  Simple Java Programs/solution.java
Labels: hacktoberfest-accepted

#2180 Added a clock app
  js/clock-app.js
Labels: hacktoberfest-accepted

#2178 kanpsack2.c
  kanpsack2.c
Labels: hacktoberfest-accepted

#2173 Cosmic15 | C++ | Matrix Chain Multiplication
  Program's_Contributed_By_Contributors/C++/matrix-chain-multiplication.cpp
Labels: hacktoberfest-accepted

#2171 Adds a C program
  Mario.c
Labels: hacktoberfest-accepted

#2170 Sorting Algorithms
  HeapSort.cpp
  MergeSort.cpp
  QuickSort.cpp
Labels: hacktoberfest-accepted

#2165 Added merge sort Algorithm in c++
  Program's_Contributed_By_Contributors/C++/merge_sort.cpp
Labels: hacktoberfest-accepted

#2163 Adds Java programs
  java programs/largest.java
Labels: hacktoberfest-accepted

#2162 Update FibonacciNumber
  FibonacciNumber
Labels: hacktoberfest-accepted

#2145 Adicionando um app para geração de senhas
  frontend projects/GeradorSenha.html
Labels: hacktoberfest-accepted

#2146 N-Queen's Problem
  Program's_Contributed_By_Contributors/Java_Programs/Data_structure/nQueen.java
Labels: hacktoberfest-accepted

#2137 add: Dice Roll Simulator
  Program's_Contributed_By_Contributors/Python_Programs/DiceRollSimulator.py
Labels: hacktoberfest-accepted

#2136 Update README.md
  README.md
Labels: hacktoberfest-accepted

#2135 made a demo login page with nice visuals and input validations.
  css/LoginPage.html
Labels: hacktoberfest-accepted

#2134 added deletion form linked list
  Program's_Contributed_By_Contributors/Implementation_of_DS/linked_list.c
  Program's_Contributed_By_Contributors/Implementation_of_DS/linked_list.exe
Labels: hacktoberfest-accepted

#2126 added students.py
  students.py
Labels: hacktoberfest-accepted

#2125 Create pattern1
  pattern1
Labels: hacktoberfest-accepted

#2123 update the alarm_clock program
  Program's_Contributed_By_Contributors/Python_Programs/alarm_clock.py
Labels: hacktoberfest-accepted

#2122 Linked List Implementation
  Program's_Contributed_By_Contributors/C++/SinglyLinkedList.cpp
Labels: hacktoberfest-accepted

#2119 Create calC
  calC
Labels: hacktoberfest-accepted

#2118 Glassmorphism-effect in CSS
  css/Glassmorphism-effect in css/index.html
  css/Glassmorphism-effect in css/readme.md
  css/Glassmorphism-effect in css/style.css
Labels: hacktoberfest-accepted

#2116 Added CPP solution for LeetCode question of Power of Four
  Program's_Contributed_By_Contributors/C++/PowerOfFour.cpp
Labels: hacktoberfest-accepted

#2114 This pull request is made by Raja-s-k
  HTML/hello-world.html
Labels: hacktoberfest-accepted

#2113 Hash Table using Templates
  Program's_Contributed_By_Contributors/HashTable.cpp
Labels: hacktoberfest-accepted

#2112 Vigenère Code Encrypter Decrypter
  vigenere_EncrypterDecrypter.py
Labels: hacktoberfest-accepted

#2111 Update data.js
  contributors/data.js
Labels: hacktoberfest-accepted

#2110 Largest Rectangle Area
  Program's_Contributed_By_Contributors/Java_Programs/Data_structure/LargestRectangle.java
Labels: hacktoberfest-accepted

#2109 Fibonacci series C++
  fibonacci series
Labels: hacktoberfest-accepted

#2107 Inorder_Preorder_Postorder_Tree_Traversal in python
  Program's_Contributed_By_Contributors/Java_Programs/.DS_Store
  Program's_Contributed_By_Contributors/Python_Programs/Inorder_Preorder_Postorder_Tree_Traversal.py
Labels: hacktoberfest-accepted

#2105 Create Binary_Palindrome.java
  Program's_Contributed_By_Contributors/Java_Programs/Data_structure/Binary_Palindrome.java
Labels: hacktoberfest-accepted

#2104 Create Greatestelement.java
  Program's_Contributed_By_Contributors/Java_Programs/Data_structure/Greatestelement.java
Labels: hacktoberfest-accepted

#2091 hacktoberfest-2022
  Program's_Contributed_By_Contributors/Python_Programs/class_constructor.py
Labels: hacktoberfest-accepted

#2090 Web scraping using python
  Program's_Contributed_By_Contributors/Python_Programs/Web_Scraping_with_BeatifulSoup.py
Labels: hacktoberfest-accepted

#2089 send email
  Program's_Contributed_By_Contributors/Python_Programs/send_email.py
Labels: hacktoberfest-accepted

#2086 Added calc files
  Calc.java
Labels: hacktoberfest-accepted

#2084 Create LongestCommonSubsequence.cpp
  LongestCommonSubsequence.cpp
Labels: hacktoberfest-accepted

#2082 Create python_calculator.py
  python_calculator.py
Labels: hacktoberfest-accepted

#2080 contribution added
  css/contributors.css
  css/style.css
Labels: hacktoberfest-accepted

#2074 Add QR code generator
  Program's_Contributed_By_Contributors/Python_Programs/qr.py
Labels: hacktoberfest-accepted

#2072 A program to calculate double digitial option price
  Program's_Contributed_By_Contributors/C++/.vscode/settings.json
  Program's_Contributed_By_Contributors/C++/.vscode/tasks.json
  Program's_Contributed_By_Contributors/C++/doubleDigitalPriceOption.cpp
Labels: hacktoberfest-accepted

#2063 Create Basic operations in a stack using call by reference
  Basic operations in a stack using call by reference
Labels: hacktoberfest-accepted

#2055 Todo List
  TODO LIST/todo.css
  TODO LIST/todo.html
  TODO LIST/todo.js
Labels: hacktoberfest-accepted

#2054 BackEnd Project
  backend projects/README.md
  backend projects/Restful-api/.gitignore
  backend projects/Restful-api/README.md
  backend projects/Restful-api/index.js
  backend projects/Restful-api/package.json
Labels: hacktoberfest-accepted

#2053 Dice Roll Game added
  DiceGame/dicee.html
  DiceGame/dicee.js
  DiceGame/images/dice1.png
  DiceGame/images/dice2.png
  DiceGame/images/dice3.png
  DiceGame/images/dice4.png
  DiceGame/images/dice5.png
  DiceGame/images/dice6.png
  DiceGame/images/favicon.ico
  DiceGame/styles.css
Labels: hacktoberfest-accepted

#2051 Binary Search Tree in C++
  Binary Search Tree in C++.cpp
Labels: hacktoberfest-accepted

#2049 Added My Tic-Tac-Toe Game
  Tic Tac Toe/Dev-tanay.md
Labels: hacktoberfest-accepted

#2048 Glowing Icons
  GlowingIcons/index.html
  GlowingIcons/style.css
Labels: hacktoberfest-accepted

#2046 Create quicksort.cpp
  quicksort.cpp
Labels: hacktoberfest-accepted

#2041 To add a Linear search program in C++
  Program's_Contributed_By_Contributors/C++/linearsearch.cpp
Labels: hacktoberfest-accepted

#2040 Create SieveofEratosthenes.java
  SieveofEratosthenes.java
Labels: hacktoberfest-accepted

#2035 IPFinder - java
  Program's_Contributed_By_Contributors/Java_Programs/Misc/IPFinder.java
Labels: hacktoberfest-accepted

#2033 Add files via upload
  linked_list.py
Labels: hacktoberfest-accepted

#2031 hacktoberfest2022
  Program's_Contributed_By_Contributors/Implementation_of_DS/traversal-tree.cpp
Labels: hacktoberfest-accepted

#2029 added Piet version of FizzBuzz
  Program's_Contributed_By_Contributors/Piet/fizzbuzz.png
  Program's_Contributed_By_Contributors/Piet/readme.txt
Labels: hacktoberfest-accepted

#2028 added bf version of FizzBuzz
  Program's_Contributed_By_Contributors/BrainFuck_Programs/FizzBuzz.bf
Labels: hacktoberfest-accepted

#2025 Number Guessing Game
  number-guessing-game.js
Labels: hacktoberfest-accepted

#2024 Added enter key functionality
  frontend projects/To-do-list/To-do-list.js
Labels: hacktoberfest-accepted

#2022 added java file
  landmines.java
Labels: hacktoberfest-accepted

#2015 Meme Generator added
  Program's_Contributed_By_Contributors/Meme-Gen/image1.png
  Program's_Contributed_By_Contributors/Meme-Gen/index.html
  Program's_Contributed_By_Contributors/Meme-Gen/sc-meme.html
  Program's_Contributed_By_Contributors/Meme-Gen/sc_meme.css
  Program's_Contributed_By_Contributors/Meme-Gen/sc_meme.js
  Program's_Contributed_By_Contributors/Meme-Gen/sc_meme/sc_meme1.png
  Program's_Contributed_By_Contributors/Meme-Gen/sc_meme/sc_meme2.png
  Program's_Contributed_By_Contributors/Meme-Gen/sc_meme/sc_meme3.png
  Program's_Contributed_By_Contributors/Meme-Gen/sc_meme/sc_meme4.png
  Program's_Contributed_By_Contributors/Meme-Gen/sc_meme/sc_meme5.png
  Program's_Contributed_By_Contributors/Meme-Gen/sc_meme/sc_meme6.png
  Program's_Contributed_By_Contributors/Meme-Gen/sc_meme/sc_meme7.png
  Program's_Contributed_By_Contributors/Meme-Gen/sc_meme/sc_meme8.png
  Program's_Contributed_By_Contributors/Meme-Gen/sc_meme/sc_meme9.png
  Program's_Contributed_By_Contributors/Meme-Gen/styles.css
  Program's_Contributed_By_Contributors/Meme-Gen/t_meme/t_meme1.png
  Program's_Contributed_By_Contributors/Meme-Gen/t_meme/t_meme10.png
  Program's_Contributed_By_Contributors/Meme-Gen/t_meme/t_meme2.png
  Program's_Contributed_By_Contributors/Meme-Gen/t_meme/t_meme3.png
  Program's_Contributed_By_Contributors/Meme-Gen/t_meme/t_meme4.png
  Program's_Contributed_By_Contributors/Meme-Gen/t_meme/t_meme5.png
  Program's_Contributed_By_Contributors/Meme-Gen/t_meme/t_meme6.png
  Program's_Contributed_By_Contributors/Meme-Gen/t_meme/t_meme7.png
  Program's_Contributed_By_Contributors/Meme-Gen/t_meme/t_meme8.png
  Program's_Contributed_By_Contributors/Meme-Gen/t_meme/t_meme9.png
  Program's_Contributed_By_Contributors/Meme-Gen/text-memes.html
  Program's_Contributed_By_Contributors/Meme-Gen/text.css
  Program's_Contributed_By_Contributors/Meme-Gen/text.js
  Program's_Contributed_By_Contributors/Meme-Gen/text_m/text_m1.png
  Program's_Contributed_By_Contributors/Meme-Gen/text_m/text_m2.png
  Program's_Contributed_By_Contributors/Meme-Gen/text_m/text_m3.png
  Program's_Contributed_By_Contributors/Meme-Gen/text_m/text_m4.png
  Program's_Contributed_By_Contributors/Meme-Gen/text_m/text_m5.png
  Program's_Contributed_By_Contributors/Meme-Gen/text_m/text_m6.png
  Program's_Contributed_By_Contributors/Meme-Gen/traditional.css
  Program's_Contributed_By_Contributors/Meme-Gen/traditional.html
  Program's_Contributed_By_Contributors/Meme-Gen/traditional.js
  Program's_Contributed_By_Contributors/Python_Programs/snake_game.py
Labels: hacktoberfest-accepted

#2013 Create mergesort.cpp
  Program's_Contributed_By_Contributors/C++/mergesort.cpp
Labels: hacktoberfest-accepted

#2009 Create Calculator.css
  css/Calculator.css
Labels: hacktoberfest-accepted

#2008 Added a random value generator
  js/GeneratesRandomValue.java
Labels: hacktoberfest-accepted

#2004 Create Css-penguin.html
  css/Css-penguin.html
Labels: hacktoberfest-accepted

#2002 Create GodDrago.html
  GodDrago.html
Labels: hacktoberfest-accepted

#2001 Create Video-audio_extractor.py
  Program's_Contributed_By_Contributors/Python_Programs/Video-audio_extractor.py
Labels: hacktoberfest-accepted

#1995 please merge my pull request
  Program's_Contributed_By_Contributors/Python_Programs/Sorting algorithm in C
  Sorting algorithm in C
Labels: hacktoberfest-accepted

#1988 Chocola Problem
  Program's_Contributed_By_Contributors/Java_Programs/Data_structure/ChocolaProblem.java
Labels: hacktoberfest-accepted

#1987 Add a webapp that shows all Pokemon Cards and Decks
  frontend projects/Pokemon TCG Collection/.gitignore
  frontend projects/Pokemon TCG Collection/README.md
  frontend projects/Pokemon TCG Collection/package-lock.json
  frontend projects/Pokemon TCG Collection/package.json
  frontend projects/Pokemon TCG Collection/public/favicon.ico
  frontend projects/Pokemon TCG Collection/public/index.html
  frontend projects/Pokemon TCG Collection/public/logo192.png
  frontend projects/Pokemon TCG Collection/public/logo512.png
  frontend projects/Pokemon TCG Collection/public/manifest.json
  frontend projects/Pokemon TCG Collection/public/robots.txt
  frontend projects/Pokemon TCG Collection/src/App.css
  frontend projects/Pokemon TCG Collection/src/App.js
  frontend projects/Pokemon TCG Collection/src/App.test.js
  frontend projects/Pokemon TCG Collection/src/components/Card.js
  frontend projects/Pokemon TCG Collection/src/components/CardView.js
  frontend projects/Pokemon TCG Collection/src/components/Cards.js
  frontend projects/Pokemon TCG Collection/src/components/Decks.js
  frontend projects/Pokemon TCG Collection/src/components/Dialog.js
  frontend projects/Pokemon TCG Collection/src/components/Footer.js
  frontend projects/Pokemon TCG Collection/src/components/Home.js
  frontend projects/Pokemon TCG Collection/src/components/Index.js
  frontend projects/Pokemon TCG Collection/src/components/Loader.js
  frontend projects/Pokemon TCG Collection/src/components/Navbar.js
  frontend projects/Pokemon TCG Collection/src/components/deck.json
  frontend projects/Pokemon TCG Collection/src/icons/bug.svg
  frontend projects/Pokemon TCG Collection/src/icons/dark.svg
  frontend projects/Pokemon TCG Collection/src/icons/dragon.svg
  frontend projects/Pokemon TCG Collection/src/icons/electric.svg
  frontend projects/Pokemon TCG Collection/src/icons/fairy.svg
  frontend projects/Pokemon TCG Collection/src/icons/fighting.svg
  frontend projects/Pokemon TCG Collection/src/icons/fire.svg
  frontend projects/Pokemon TCG Collection/src/icons/flying.svg
  frontend projects/Pokemon TCG Collection/src/icons/ghost.svg
  frontend projects/Pokemon TCG Collection/src/icons/grass.svg
  frontend projects/Pokemon TCG Collection/src/icons/ground.svg
  frontend projects/Pokemon TCG Collection/src/icons/ice.svg
  frontend projects/Pokemon TCG Collection/src/icons/icons.js
  frontend projects/Pokemon TCG Collection/src/icons/normal.svg
  frontend projects/Pokemon TCG Collection/src/icons/poison.svg
  frontend projects/Pokemon TCG Collection/src/icons/psychic.svg
  frontend projects/Pokemon TCG Collection/src/icons/rock.svg
  frontend projects/Pokemon TCG Collection/src/icons/steel.svg
  frontend projects/Pokemon TCG Collection/src/icons/water.svg
  frontend projects/Pokemon TCG Collection/src/index.css
  frontend projects/Pokemon TCG Collection/src/index.js
  frontend projects/Pokemon TCG Collection/src/logo.svg
  frontend projects/Pokemon TCG Collection/src/reportWebVitals.js
  frontend projects/Pokemon TCG Collection/src/setupTests.js
  frontend projects/Pokemon TCG Collection/src/styles/card.css
  frontend projects/Pokemon TCG Collection/src/styles/home.css
  frontend projects/Pokemon TCG Collection/src/styles/style.css
Labels: hacktoberfest-accepted

#1982 Create snake water game
  Program's_Contributed_By_Contributors/Python_Programs/snake water game
Labels: hacktoberfest-accepted

#1981 CPP Trapping Rain Water Solution
  Program's_Contributed_By_Contributors/C++/Trapping_RainWater.cpp
Labels: hacktoberfest-accepted

#1980 Update FibonacciNumber (added second appraoch)
  FibonacciNumber
Labels: hacktoberfest-accepted

#1977 palindrome changed
  Program's_Contributed_By_Contributors/Python_Programs/Palindrome.py
Labels: hacktoberfest-accepted

#1975 2nd largest in the array
  Program's_Contributed_By_Contributors/Python_Programs/2nd largest in the array.py
Labels: hacktoberfest-accepted

#1972 Create 3d_object_detection_classifier.py
  Program's_Contributed_By_Contributors/Python_Programs/3d_object_detection_classifier.py
Labels: hacktoberfest-accepted

#1966 Python: Translate String
  translate.py
Labels: hacktoberfest-accepted

#1965 Update style.css
  css/style.css
Labels: hacktoberfest-accepted

#1962 Adds python implementation for battleship game
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/.coverage
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/.coveragerc
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/.idea/encodings.xml
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/.idea/inspectionProfiles/profiles_settings.xml
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/.idea/modules.xml
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/.idea/workspace.xml
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/BattleArea.py
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/Gameplay.py
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/Player.py
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/ReadMe.md
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/Ship.py
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/Utilities.py
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/__pycache__/BattleArea.cpython-36.pyc
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/__pycache__/Player.cpython-36.pyc
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/__pycache__/Ship.cpython-36.pyc
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/__pycache__/Utilities.cpython-36.pyc
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/BattleArea_py.html
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/Gameplay_py.html
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/Player_py.html
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/Ship_py.html
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/Utilities_py.html
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/coverage_html.js
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/index.html
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/jquery.ba-throttle-debounce.min.js
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/jquery.hotkeys.js
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/jquery.isonscreen.js
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/jquery.min.js
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/jquery.tablesorter.min.js
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/keybd_closed.png
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/keybd_open.png
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/status.json
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/style.css
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/tests___init___py.html
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/tests_test_battlearea_py.html
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/unit_tests___init___py.html
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/htmlcov/unit_tests_test_battlearea_py.html
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/outputs/testdata.txt
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/testdata/testdata.txt
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/__init__.py
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/__pycache__/__init__.cpython-36.pyc
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/__pycache__/test_battlearea.cpython-36.pyc
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/__pycache__/test_game_play.cpython-36.pyc
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/__pycache__/test_player.cpython-36.pyc
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/__pycache__/test_ship.cpython-36.pyc
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/__pycache__/test_utilities.cpython-36.pyc
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/test_battlearea.py
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/test_game_play.py
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/test_player.py
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/test_ship.py
  Program's_Contributed_By_Contributors/Python_Programs/Battleship/tests/test_utilities.py
Labels: hacktoberfest-accepted

#1961 Add files via upload
  clac.js
  index.html
  style.css
Labels: hacktoberfest-accepted

#1951 Word slicer
  Program's_Contributed_By_Contributors/JavaScript_Programs/word-slicer.js
Labels: hacktoberfest-accepted

#1949 Add spellchecking to be true in input field of To-do-list
  frontend projects/To-do-list/To-do-list.html
Labels: hacktoberfest-accepted

#2322 hacktoberfest
  OtpGenratorCode
  Patternproblem
  PriopertyQueue
  System.md
  design.md
  pattern in java
  sdfghjkdfghj.c
  third.c
  uidesign.md
Labels: hacktoberfest-accepted

#2325 added vigenere cipher
  js/VigenereCipher.js
Labels: hacktoberfest-accepted

#2327 Create Tic_Tac_Toe_Game.cpp
  Program's_Contributed_By_Contributors/C++/Tic_Tac_Toe_Game.cpp
Labels: hacktoberfest-accepted

#2334 Update Bubble_Sort.cpp
  Program's_Contributed_By_Contributors/C++/Bubble_Sort.cpp
Labels: hacktoberfest-accepted

#2335 Create merge_sort.py
  Program's_Contributed_By_Contributors/Python_Programs/merge_sort.py
Labels: hacktoberfest-accepted

#2336 Create quick_sort.py
  Program's_Contributed_By_Contributors/Python_Programs/quick_sort.py
Labels: hacktoberfest-accepted

#2344 added Chat interface using Socket Programming
  Program's_Contributed_By_Contributors/Java_Programs/SocketProgramming/Client.java
  Program's_Contributed_By_Contributors/Java_Programs/SocketProgramming/Server.java
Labels: hacktoberfest-accepted

#2350 Added Dijkstra's Algorithm
  Program's_Contributed_By_Contributors/C++/Dijkstra's Algorithm.cpp
Labels: hacktoberfest-accepted

#2540 Create armstrong.cpp
  Program's_Contributed_By_Contributors/C++/armstrong.cpp
Labels: hacktoberfest-accepted

#2539 Bubble sort in js
  Program's_Contributed_By_Contributors/JavaScript_Programs/bubble-sort-in-js.js
Labels: hacktoberfest-accepted

#2538 Depth First Search(Weighted Graph)
  Program's_Contributed_By_Contributors/Python_Programs/Depth First Search(Weighted Graph).py
Labels: hacktoberfest-accepted

#2535 ADDED A NEW FILE "eyes that follow"
  eyes-that-follow.html
Labels: hacktoberfest-accepted

#2536 fizzbuzz rust
  Program's_Contributed_By_Contributors/Rust_Programs/fizzbuzz.rs
Labels: hacktoberfest-accepted

#2526 Java programs added
  Program's_Contributed_By_Contributors/Java_Programs/Armstrong.class
  Program's_Contributed_By_Contributors/Java_Programs/Calculator.class
  Program's_Contributed_By_Contributors/Java_Programs/Complex$ComplexNumber.class
  Program's_Contributed_By_Contributors/Java_Programs/Complex.class
  Program's_Contributed_By_Contributors/Java_Programs/CountNums.class
  Program's_Contributed_By_Contributors/Java_Programs/Main.class
  Program's_Contributed_By_Contributors/Java_Programs/Reverse.class
  Program's_Contributed_By_Contributors/Java_Programs/Sum_of_Fibonacci.class
  Program's_Contributed_By_Contributors/Java_Programs/Switch_case.class
  Program's_Contributed_By_Contributors/Java_Programs/Test.class
  Program's_Contributed_By_Contributors/Java_Programs/UpperORLowercase.class
  Program's_Contributed_By_Contributors/Java_Programs/inputs.class
  Program's_Contributed_By_Contributors/Java_Programs/isPrime.class
  Program's_Contributed_By_Contributors/Java_Programs/max3.class
  Program's_Contributed_By_Contributors/Java_Programs/prime.class
  Program's_Contributed_By_Contributors/Java_Programs/sum.class
Labels: hacktoberfest-accepted

#2524 Create Kruskal's ALgorithm.cpp
  Program's_Contributed_By_Contributors/C++/Kruskal's ALgorithm.cpp
Labels: hacktoberfest-accepted

#2523 Create Prim's Algorithm.cpp
  Program's_Contributed_By_Contributors/C++/Prim's Algorithm.cpp
Labels: hacktoberfest-accepted

#2517 Update many_pattern.cpp
  Program's_Contributed_By_Contributors/C++/many_pattern.cpp
Labels: hacktoberfest-accepted

#2514 Added Kenny to contributorsList.js
  contributors/contributorsList.js
Labels: hacktoberfest-accepted

#2508 N-queens problem using python
  Program's_Contributed_By_Contributors/Python_Programs/n-queens.py
Labels: hacktoberfest-accepted

#2551 added in contributor.json and fixed id in file
  contributors/contributorsList.js
Labels: hacktoberfest-accepted

#1802 RadixSort
  Program's_Contributed_By_Contributors/Java_Programs/Data_structure/RevLinkList.java
  Program's_Contributed_By_Contributors/Python_Programs/RadixSort.py
Labels: hacktoberfest-accepted

#2779 Shell sort
  Program's_Contributed_By_Contributors/C++/Radix_Sort.cpp
  Program's_Contributed_By_Contributors/C++/heap_sort.cpp
  Program's_Contributed_By_Contributors/C++/selection_sort.cpp
  Program's_Contributed_By_Contributors/C++/shell_sort.cpp
Labels: hacktoberfest-accepted

#2778 Calculating area of shapes using Interfaces in go.
  Program's_Contributed_By_Contributors/Golang Programs/areaFigure.go
Labels: hacktoberfest-accepted

#2777 Adding Couting Sort implementation in c++
  Program's_Contributed_By_Contributors/C++/counting_sort.cpp
Labels: hacktoberfest-accepted

#2776 C++ program for recursive implementation of Bubble sort
  Program's_Contributed_By_Contributors/C++/recursive_bubble_sort.cpp
Labels: hacktoberfest-accepted

#2774 Added countSmallestElement.cpp
  Program's_Contributed_By_Contributors/C++/countSmallestElement.cpp
Labels: hacktoberfest-accepted

#2783 Feat: Added for Hacktoberfest 2022
  contributors/contributorsList.js
Labels: hacktoberfest-accepted

#2920 Addition_without_arithmetic
  Program's_Contributed_By_Contributors/Java_Programs/Addition without arithmetic operation
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2874 Want to add weight convertor GUI
  Program's_Contributed_By_Contributors/Python_Programs/leap year.py
  Program's_Contributed_By_Contributors/Python_Programs/weight_convertor_gui.py
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2921 New python file djikstra.py
  Program's_Contributed_By_Contributors/Python_Programs/djikstra.py
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2919 Create merge_linked_list.cpp
  Program's_Contributed_By_Contributors/C++/dynamic_prrogramming.cpp
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2918 Balance Paranthesis.cpp
  Program's_Contributed_By_Contributors/C++/balanceParanthesis.cpp
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2916 Issue #2911-Added Level Order Traversal for Binary Tree in Python
  Program's_Contributed_By_Contributors/Python_Programs/Level_order_traversal_binary_tree.py
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2915 I add myself to contributors
  contributors/contributorsList.js
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2910 Lyrics Finder using Python
  Program's_Contributed_By_Contributors/Python_Programs/lyrics_scrapper.py
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2907 merge_sort.cpp
  Program's_Contributed_By_Contributors/C++/Merge_Sort.java
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2906 fibonacci_DP.cpp
  Program's_Contributed_By_Contributors/C++/Fibonacci_using_DP.c++
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2897 BST to maxheap GFG
  BSTtoMaxheap.cpp
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2891 Added Median Of Two Sorted Array program
  Program's_Contributed_By_Contributors/C++/MedianOfTwoSortedArray.c++
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2889 Added Typing effect , fixes #2319
  Program's_Contributed_By_Contributors/Typing-effect-website/index.html
  Program's_Contributed_By_Contributors/Typing-effect-website/index.js
  Program's_Contributed_By_Contributors/Typing-effect-website/style.css
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2888 Update Contributor List
  contributors/contributorsList.js
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2890 Added new Project file and Added new Contributor to List
  Program's_Contributed_By_Contributors/Python_Programs/Calculator.py
  contributors/contributorsList.js
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2892 added target-sum.cpp
  Program's_Contributed_By_Contributors/C++/target-sum.cpp
  contributors/contributorsList.js
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2894 Added name to contributor's list and a new project file
  Program's_Contributed_By_Contributors/Python_Programs/QuickSort.py
  contributors/contributorsList.js
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2896 added a cpp program for calculating total hamming distance
  Program's_Contributed_By_Contributors/C++/Total hamming distance.cpp
  contributors/contributorsList.js
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2900 Added the Details in contributors List
  contributors/contributorsList.js
Labels: Star ⭐️ the repo to earn hacktoberfest label

#2837 solution for TrappedRainWater in java
  Program's_Contributed_By_Contributors/Java_Programs/Data_structure/TrappingRainWater_problem.java
Labels: hacktoberfest-accepted

#2913 Adding my name to the contributor list
  contributors/contributorsList.js
Labels: Star ⭐️ the repo to earn hacktoberfest label
